# Generated by Django 5.2.4 on 2025-07-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program_type',
            field=models.CharField(choices=[('degree', 'Degree Program'), ('diploma', 'Diploma Program')], default='degree', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
    ]
