# Generated by Django 5.2.4 on 2025-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_program_type_and_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.TextField(blank=True, null=True),
        ),
    ]
