# Generated by Django 5.2.4 on 2025-07-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_department_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='department',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology')], default='computer_science', max_length=50),
        ),
    ]
