# Generated by Django 5.2.4 on 2025-07-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supervisor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='department',
            field=models.CharField(blank=True, help_text='Department or faculty the supervisor belongs to', max_length=100, null=True),
        ),
    ]
