# Generated by Django 5.2.4 on 2025-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_supervisor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attachment_period',
            field=models.CharField(blank=True, choices=[('Jan-Apr', 'January - April'), ('May-Aug', 'May - August'), ('Sep-Dec', 'September - December')], max_length=10, null=True),
        ),
    ]
