# Generated by Django 5.2.4 on 2025-07-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_supervision_visits'),
        ('core', '0006_student_attachment_period'),
    ]

    operations = [
    ]
