# Generated by Django 5.2.4 on 2025-07-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250727_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('supervisor', 'Supervisor'), ('dean', 'Dean')], max_length=20),
        ),
    ]
