# Generated by Django 5.2.4 on 2025-07-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_dean_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Combined grade from both lecturer evaluations', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='grade_calculation_details',
            field=models.JSONField(blank=True, help_text='Details of how the final grade was calculated', null=True),
        ),
    ]
